on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: './.github/actions/issue'
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          test_param_with_underscore: testParam
          title: title
          body: body
          assignees: |
            tichon29
      - run: echo ${{steps.issue.outputs.issue}}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Jean-Pierre"
      - run: echo "${{ steps.hello.outputs.time }}"
      - run: echo $HELLO