name: Open Github issue
author: Stephane Hervochon
description: Open a github issue
inputs:
  token:
    description: 'Github token'
    required: true
  title:
    description: 'Issue Title'
    required: true
  body:
    description: 'Issue Body'
  assignees:
    description: 'Issue Assignees'
outputs:
  issue:
    description: 'The issue object as a json string'
runs:
  using: "node12"
  main: "dist/index.js"